import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs"
import { type NextPage } from "next"
import Head from "next/head"
import Link from "next/link"

import { api } from "~/utils/api"

const CreatPostWizard = {
  //
}

const Home: NextPage = () => {
  const user = useUser()
  const { data, isLoading } = api.posts.getAll.useQuery()

  if (isLoading) return <div>Loading...</div>
  if (!data) return <div>Something Went Wrong</div>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex  border-b border-slate-400 p-4">
            <div className="flex justify-center">
              {!user.isSignedIn && <SignInButton />}
            </div>
            {!!user.isSignedIn && <SignOutButton />}
          </div>
          <div className="flex flex-col">
            {data.map((post) => (
              <div className="border-b border-slate-400 p-8" key={post.id}>
                {post.content}
              </div>
            ))}
          </div>
        </div>
        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
      </main>
    </>
  )
}

export default Home
